[package]
name = "foogold"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bip39 = "1.0.1"
bitcoin = "0.29.2"
frankenstein = "0.23.0"
rand = "0.6.0"
typed-builder = "0.12.0"